FROM mongo:4.4

# Install snapd
RUN apt-get update
RUN apt-get install curl

# official source of node 18, i found it manually
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs



# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the Express app files to the container
COPY . .




# Seed the database
#CMD ["node", "word_relationships_GPT.js"]
#CMD ["sh", "-c", "sleep 20 && node word_relationships_GPT.js"]
