version: '3'
services:
  curl-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_IP=10.0.2.15
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
